import { prisma } from "../lib/prisma.js";

async function resolveSellerId(): Promise<string> {
  const email = process.env.SEED_SELLER_EMAIL
  if (email) {
    const seller = await prisma.user.findUnique({ where: { email } })
    if (seller) return seller.id
    console.warn(`⚠ SEED_SELLER_EMAIL "${email}" not found in DB, falling back to first SELLER`)
  }
  const first = await prisma.user.findFirst({ where: { role: "SELLER" }, orderBy: { createdAt: "asc" } })
  if (first) return first.id
  throw new Error("No SELLER account found. Create a seller account first, then re-run the seed.")
}

// ── Step 1: Categories ────────────────────────────────────────────────────────
const categories = [
  { name: "Pain Relief",            slug: "pain-relief",            description: "Medicines for pain management and relief" },
  { name: "Cold & Flu",             slug: "cold-flu",               description: "Medicines for cold, flu, and allergy relief" },
  { name: "Vitamins & Supplements", slug: "vitamins-supplements",   description: "Essential vitamins, minerals and health supplements" },
  { name: "Digestive Health",       slug: "digestive-health",       description: "Medicines for digestive issues and gut health" },
  { name: "Skin Care",              slug: "skin-care",              description: "Topical medicines and creams for skin conditions" },
  { name: "Diabetes Care",          slug: "diabetes-care",          description: "Medicines and devices for diabetes management" },
  { name: "Heart Health",           slug: "heart-health",           description: "Cardiovascular medicines and supplements" },
  { name: "Eye Care",               slug: "eye-care",               description: "Eye drops, supplements and vision care products" },
  { name: "Baby Care",              slug: "baby-care",              description: "Safe medicines and supplements for infants and toddlers" },
  { name: "Antibiotics",            slug: "antibiotics",            description: "Prescription antibiotics for bacterial infections" },
  { name: "First Aid",              slug: "first-aid",              description: "Antiseptics, bandages and wound care products" },
  { name: "Mental Wellness",        slug: "mental-wellness",        description: "Supplements for sleep, stress and mental health" },
]

// ── Step 2: Medicines ─────────────────────────────────────────────────────────
const medicines = [
  // ── Pain Relief ─────────────────────────────────────────────────────────────
  {
    name: "Napa Extra", slug: "napa-extra",
    description: "Fast-acting relief for headache, toothache, and body pain. Contains Paracetamol 500mg + Caffeine 65mg.",
    price: 45, stock: 150, image: null, images: [],
    manufacturer: "Beximco Pharma", dosage: "1-2 tablets every 4-6 hours", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Fast Relief", "Popular Choice", "#1 in Pain Relief"],
    uses: ["Headache", "Toothache", "Fever", "Body pain", "Menstrual cramps"],
    ingredients: "Paracetamol 500mg, Caffeine 65mg",
    sideEffects: ["Nausea (rare)", "Stomach upset", "Allergic reaction (very rare)", "Liver issues on overdose"],
    storage: "Store below 25°C in a cool, dry place. Keep away from direct sunlight and moisture.",
    dosageAdults: "1–2 tablets every 4–6 hours as needed",
    dosageChildren: "Not recommended for children under 12 without medical advice",
    dosageMaxDaily: "Maximum 8 tablets (4g paracetamol) per 24 hours",
    dosageNotes: "Take with or after food to reduce stomach upset. Do not exceed recommended dose.",
    categorySlug: "pain-relief",
  },
  {
    name: "Ace Plus", slug: "ace-plus",
    description: "Anti-inflammatory pain relief for muscle and joint pain. Ibuprofen 400mg.",
    price: 60, stock: 95, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 tablet 3 times daily", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Anti-Inflammatory", "Fast Acting"],
    uses: ["Muscle pain", "Joint pain", "Arthritis", "Back pain", "Dental pain"],
    ingredients: "Ibuprofen 400mg",
    sideEffects: ["Stomach pain", "Heartburn", "Nausea", "Dizziness", "Mild headache"],
    storage: "Store at room temperature (15–25°C). Keep away from moisture.",
    dosageAdults: "1 tablet 3 times daily with food",
    dosageChildren: "Not recommended under 12 years",
    dosageMaxDaily: "Maximum 3 tablets per 24 hours",
    dosageNotes: "Always take with food or milk to protect stomach lining.",
    categorySlug: "pain-relief",
  },
  {
    name: "Voltalin Gel", slug: "voltalin-gel",
    description: "Topical gel for localized pain and inflammation relief. Diclofenac Sodium 1%.",
    price: 120, stock: 60, image: null, images: [],
    manufacturer: "Novartis", dosage: "Apply 3-4 times daily", form: "Cream",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Topical Relief", "No Drowsiness"],
    uses: ["Joint pain", "Muscle pain", "Sports injuries", "Back pain"],
    ingredients: "Diclofenac Sodium 1%",
    sideEffects: ["Skin irritation (rare)", "Redness at application site"],
    storage: "Store below 25°C. Keep away from eyes and mucous membranes.",
    dosageAdults: "Apply a thin layer 3–4 times daily to affected area",
    dosageChildren: "Not recommended under 14 years",
    dosageMaxDaily: null,
    dosageNotes: "Wash hands after application. Avoid contact with eyes.",
    categorySlug: "pain-relief",
  },
  {
    name: "Maxpro", slug: "maxpro",
    description: "Long-lasting pain relief for arthritis and menstrual cramps. Naproxen 250mg.",
    price: 85, stock: 0, image: null, images: [],
    manufacturer: "Incepta Pharma", dosage: "1 tablet twice daily", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Long-Lasting", "12hr Relief"],
    uses: ["Arthritis", "Menstrual cramps", "Muscle pain", "Tendonitis"],
    ingredients: "Naproxen Sodium 250mg",
    sideEffects: ["Stomach upset", "Nausea", "Headache", "Dizziness"],
    storage: "Store at room temperature away from moisture and light.",
    dosageAdults: "1 tablet twice daily with food",
    dosageChildren: "Not recommended under 12 years",
    dosageMaxDaily: "Maximum 2 tablets per 24 hours",
    dosageNotes: "Take with food or milk. Avoid alcohol.",
    categorySlug: "pain-relief",
  },
  {
    name: "Flexon MR", slug: "flexon-mr",
    description: "Muscle relaxant for back pain and spasms. Ibuprofen + Paracetamol + Chlorzoxazone.",
    price: 95, stock: 120, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "1 tablet 3 times daily", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: true,
    keyBadges: ["Muscle Relaxant", "Triple Action"],
    uses: ["Back pain", "Muscle spasms", "Neck pain", "Sprains"],
    ingredients: "Ibuprofen 400mg + Paracetamol 325mg + Chlorzoxazone 250mg",
    sideEffects: ["Drowsiness", "Dizziness", "Stomach upset", "Dry mouth"],
    storage: "Store below 30°C. Keep in a dry place.",
    dosageAdults: "1 tablet 3 times daily after meals",
    dosageChildren: "Not recommended",
    dosageMaxDaily: "Maximum 3 tablets per 24 hours",
    dosageNotes: "May cause drowsiness. Do not drive or operate machinery.",
    categorySlug: "pain-relief",
  },

  // ── Cold & Flu ───────────────────────────────────────────────────────────────
  {
    name: "Fexo 120", slug: "fexo-120",
    description: "Non-drowsy antihistamine for seasonal allergies. Fexofenadine 120mg.",
    price: 70, stock: 200, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 tablet daily", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Non-Drowsy", "24hr Relief", "Popular Choice"],
    uses: ["Seasonal allergies", "Hay fever", "Allergic rhinitis", "Hives", "Itching"],
    ingredients: "Fexofenadine Hydrochloride 120mg",
    sideEffects: ["Headache (occasional)", "Nausea (rare)", "Dry mouth (rare)"],
    storage: "Store below 30°C. Keep in original packaging away from light.",
    dosageAdults: "1 tablet once daily, preferably in the morning",
    dosageChildren: "Not recommended under 12 years",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "Can be taken with or without food. Avoid taking with fruit juices.",
    categorySlug: "cold-flu",
  },
  {
    name: "Histacin", slug: "histacin",
    description: "24-hour allergy relief for runny nose and sneezing. Cetirizine 10mg.",
    price: 35, stock: 180, image: null, images: [],
    manufacturer: "ACI Pharma", dosage: "1 tablet at bedtime", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["24hr Relief", "Affordable"],
    uses: ["Runny nose", "Sneezing", "Allergic rhinitis", "Watery eyes", "Hives"],
    ingredients: "Cetirizine Hydrochloride 10mg",
    sideEffects: ["Mild drowsiness", "Dry mouth", "Headache (rare)"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet once daily at bedtime",
    dosageChildren: "Half tablet for ages 6–12, consult doctor under 6",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "May cause mild drowsiness. Take at bedtime if needed.",
    categorySlug: "cold-flu",
  },
  {
    name: "Tusca DX", slug: "tusca-dx",
    description: "Cough suppressant with nasal decongestant. Dextromethorphan + Phenylephrine.",
    price: 90, stock: 75, image: null, images: [],
    manufacturer: "Beximco Pharma", dosage: "10ml every 6 hours", form: "Syrup",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Cough Relief", "Decongestant"],
    uses: ["Dry cough", "Nasal congestion", "Cold symptoms", "Flu"],
    ingredients: "Dextromethorphan 15mg + Phenylephrine 5mg per 10ml",
    sideEffects: ["Drowsiness", "Nausea", "Dizziness", "Dry mouth"],
    storage: "Store below 25°C. Shake well before use.",
    dosageAdults: "10ml every 6 hours",
    dosageChildren: "5ml every 6–8 hours for ages 6–12",
    dosageMaxDaily: "Maximum 4 doses per 24 hours",
    dosageNotes: "Do not exceed recommended dose. Avoid alcohol.",
    categorySlug: "cold-flu",
  },
  {
    name: "Nasoclear Spray", slug: "nasoclear",
    description: "Fast nasal congestion relief spray. Oxymetazoline HCl 0.05%.",
    price: 145, stock: 55, image: null, images: [],
    manufacturer: "Renata Pharma", dosage: "2-3 sprays per nostril", form: "Spray",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Fast Acting", "12hr Relief"],
    uses: ["Nasal congestion", "Blocked nose", "Sinusitis", "Cold symptoms"],
    ingredients: "Oxymetazoline Hydrochloride 0.05%",
    sideEffects: ["Nasal dryness", "Burning sensation (mild)", "Rebound congestion if overused"],
    storage: "Store below 30°C. Do not freeze.",
    dosageAdults: "2–3 sprays per nostril twice daily",
    dosageChildren: "Not recommended under 6 years",
    dosageMaxDaily: "Do not use for more than 3 consecutive days",
    dosageNotes: "Do not use for more than 3 days to avoid rebound congestion.",
    categorySlug: "cold-flu",
  },
  {
    name: "Coldex", slug: "coldex",
    description: "All-in-one cold, flu and fever combination tablet.",
    price: 55, stock: 300, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 tablet 3 times daily", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["All-in-One", "Popular Choice"],
    uses: ["Cold", "Flu", "Fever", "Runny nose", "Sneezing", "Body ache"],
    ingredients: "Paracetamol 500mg + Chlorpheniramine 2mg + Pseudoephedrine 30mg",
    sideEffects: ["Drowsiness", "Dry mouth", "Dizziness", "Insomnia"],
    storage: "Store below 25°C in a dry place away from light.",
    dosageAdults: "1 tablet 3 times daily",
    dosageChildren: "Half tablet for ages 6–12",
    dosageMaxDaily: "Maximum 3 tablets per 24 hours",
    dosageNotes: "May cause drowsiness. Avoid driving after taking.",
    categorySlug: "cold-flu",
  },

  // ── Vitamins & Supplements ───────────────────────────────────────────────────
  {
    name: "D-Rise 2000", slug: "d-rise-2000",
    description: "Essential vitamin D for bone health and immunity. Vitamin D3 2000 IU.",
    price: 250, stock: 90, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "1 capsule daily", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Bone Health", "Immunity Boost", "Best Seller"],
    uses: ["Vitamin D deficiency", "Bone health", "Immunity support", "Muscle function"],
    ingredients: "Cholecalciferol (Vitamin D3) 2000 IU",
    sideEffects: ["Nausea on overdose", "Hypercalcemia if overused"],
    storage: "Store in a cool dry place below 25°C. Protect from light.",
    dosageAdults: "1 capsule daily with a meal",
    dosageChildren: "400–1000 IU daily for children, consult doctor",
    dosageMaxDaily: "Maximum 4000 IU per day unless prescribed",
    dosageNotes: "Best absorbed when taken with a fatty meal.",
    categorySlug: "vitamins-supplements",
  },
  {
    name: "Calbo-D", slug: "calbo-d",
    description: "Calcium and vitamin D combination for strong bones. Calcium 600mg + Vitamin D3.",
    price: 320, stock: 65, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 tablet twice daily", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Bone Strength", "Dual Action"],
    uses: ["Osteoporosis prevention", "Calcium deficiency", "Bone health", "Pregnancy support"],
    ingredients: "Calcium Carbonate 600mg + Vitamin D3 400 IU",
    sideEffects: ["Constipation", "Gas", "Nausea (rare)"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet twice daily with meals",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: "Maximum 2 tablets per 24 hours",
    dosageNotes: "Take with plenty of water. Space doses 4–6 hours apart.",
    categorySlug: "vitamins-supplements",
  },
  {
    name: "Multivit Gold", slug: "multivit-gold",
    description: "Complete daily nutrition with 23 essential vitamins and minerals.",
    price: 450, stock: 40, image: null, images: [],
    manufacturer: "BioVita", dosage: "1 tablet daily after meal", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["23 Vitamins", "Daily Nutrition"],
    uses: ["Daily nutrition", "Energy boost", "Immune support", "Antioxidant protection"],
    ingredients: "Vitamins A, B-complex, C, D, E, K + Zinc, Iron, Magnesium, Selenium",
    sideEffects: ["Mild nausea if taken on empty stomach", "Urine discoloration (harmless)"],
    storage: "Store in a cool dry place below 30°C.",
    dosageAdults: "1 tablet daily after a meal",
    dosageChildren: "Not recommended under 12 years",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "Best taken in the morning with breakfast.",
    categorySlug: "vitamins-supplements",
  },
  {
    name: "Ferogen XT", slug: "ferogen-xt",
    description: "Iron supplement for anemia and pregnancy support. Ferrous Ascorbate + Folic Acid.",
    price: 180, stock: 110, image: null, images: [],
    manufacturer: "Incepta Pharma", dosage: "1 tablet daily", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Iron Rich", "Pregnancy Safe"],
    uses: ["Iron deficiency anemia", "Pregnancy support", "Fatigue", "Weakness"],
    ingredients: "Ferrous Ascorbate 100mg + Folic Acid 1.5mg",
    sideEffects: ["Dark stools (harmless)", "Constipation", "Stomach upset", "Nausea"],
    storage: "Store below 25°C in a dry place. Keep away from children.",
    dosageAdults: "1 tablet daily after meals",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "Take after meals to reduce stomach upset. Avoid antacids within 2 hours.",
    categorySlug: "vitamins-supplements",
  },
  {
    name: "Omega-3 Plus", slug: "omega-3-plus",
    description: "Heart-healthy omega-3 fatty acids from deep sea fish oil. EPA + DHA 1000mg.",
    price: 520, stock: 0, image: null, images: [],
    manufacturer: "BioVita", dosage: "1 softgel twice daily", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Heart Health", "EPA + DHA", "Deep Sea"],
    uses: ["Heart health", "Cholesterol management", "Joint health", "Brain function"],
    ingredients: "Fish Oil 1000mg (EPA 180mg + DHA 120mg)",
    sideEffects: ["Fishy aftertaste", "Mild nausea", "Loose stools (high dose)"],
    storage: "Store in a cool dry place below 25°C. Refrigerate after opening.",
    dosageAdults: "1 softgel twice daily with meals",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: "Maximum 2 softgels per 24 hours",
    dosageNotes: "Take with meals to reduce fishy aftertaste.",
    categorySlug: "vitamins-supplements",
  },

  // ── Digestive Health ─────────────────────────────────────────────────────────
  {
    name: "Omeprol 20", slug: "omeprol-20",
    description: "Proton pump inhibitor for acid reflux and ulcers. Omeprazole 20mg.",
    price: 65, stock: 250, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 capsule before breakfast", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Acid Relief", "PPI", "Popular"],
    uses: ["Acid reflux", "GERD", "Peptic ulcer", "Heartburn", "Indigestion"],
    ingredients: "Omeprazole 20mg",
    sideEffects: ["Headache", "Diarrhea", "Nausea", "Abdominal pain (rare)"],
    storage: "Store below 25°C in a dry place. Keep in original packaging.",
    dosageAdults: "1 capsule once daily before breakfast",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: "Maximum 1 capsule per 24 hours for OTC use",
    dosageNotes: "Take 30 minutes before eating for best effect.",
    categorySlug: "digestive-health",
  },
  {
    name: "Antacid Plus", slug: "antacid-plus",
    description: "Quick relief from heartburn, acid indigestion and gas.",
    price: 40, stock: 180, image: null, images: [],
    manufacturer: "ACI Pharma", dosage: "10-20ml after meals", form: "Syrup",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Instant Relief", "Safe for All"],
    uses: ["Heartburn", "Acid indigestion", "Gas", "Bloating", "Stomach pain"],
    ingredients: "Aluminum Hydroxide 200mg + Magnesium Hydroxide 200mg per 10ml",
    sideEffects: ["Constipation", "Diarrhea", "Chalky taste"],
    storage: "Store below 30°C. Shake well before use.",
    dosageAdults: "10–20ml 3–4 times daily after meals and at bedtime",
    dosageChildren: "5–10ml 3 times daily, consult doctor under 6",
    dosageMaxDaily: "Maximum 80ml per 24 hours",
    dosageNotes: "Shake well before use. Do not take within 2 hours of other medicines.",
    categorySlug: "digestive-health",
  },
  {
    name: "Moticon", slug: "moticon",
    description: "Anti-nausea and vomiting relief, promotes gastric motility. Domperidone 10mg.",
    price: 50, stock: 130, image: null, images: [],
    manufacturer: "Renata Pharma", dosage: "1 tablet before meals", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Anti-Nausea", "Fast Relief"],
    uses: ["Nausea", "Vomiting", "Bloating", "Gastroparesis", "Indigestion"],
    ingredients: "Domperidone 10mg",
    sideEffects: ["Dry mouth", "Headache", "Diarrhea (rare)"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet 15–30 minutes before meals, up to 3 times daily",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: "Maximum 3 tablets per 24 hours",
    dosageNotes: "Take before meals for best effect.",
    categorySlug: "digestive-health",
  },
  {
    name: "Enzyplex", slug: "enzyplex",
    description: "Multi-enzyme formula for better digestion and nutrient absorption.",
    price: 180, stock: 70, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "1 capsule with each meal", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Multi-Enzyme", "Better Absorption"],
    uses: ["Poor digestion", "Bloating", "Gas", "Nutrient malabsorption", "Pancreatic insufficiency"],
    ingredients: "Amylase 4500 IU + Protease 250 IU + Lipase 250 IU",
    sideEffects: ["Nausea (rare)", "Abdominal cramps (rare)"],
    storage: "Store in a cool dry place below 25°C.",
    dosageAdults: "1 capsule with each main meal",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: "Maximum 3 capsules per 24 hours",
    dosageNotes: "Swallow whole with water. Do not crush or chew.",
    categorySlug: "digestive-health",
  },

  // ── Skin Care ────────────────────────────────────────────────────────────────
  {
    name: "Dermacort", slug: "dermacort",
    description: "Topical corticosteroid for eczema, rash and skin irritation. Hydrocortisone 1%.",
    price: 95, stock: 85, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "Apply thin layer 2-3 times daily", form: "Cream",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Anti-Inflammatory", "Itch Relief"],
    uses: ["Eczema", "Dermatitis", "Psoriasis", "Allergic rash", "Insect bites"],
    ingredients: "Hydrocortisone 1%",
    sideEffects: ["Skin thinning (prolonged use)", "Mild burning", "Dryness"],
    storage: "Store below 25°C. Do not freeze.",
    dosageAdults: "Apply a thin layer 2–3 times daily to affected area",
    dosageChildren: "Use with caution. Consult doctor before use in children",
    dosageMaxDaily: null,
    dosageNotes: "Do not use on face for more than 7 days. Avoid broken skin.",
    categorySlug: "skin-care",
  },
  {
    name: "Ketozol Cream", slug: "ketozol",
    description: "Antifungal cream for ringworm, athlete's foot and fungal infections. Ketoconazole 2%.",
    price: 110, stock: 95, image: null, images: [],
    manufacturer: "Beximco Pharma", dosage: "Apply once daily for 2-4 weeks", form: "Cream",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Antifungal", "Clinically Proven"],
    uses: ["Ringworm", "Athlete's foot", "Jock itch", "Fungal skin infection", "Dandruff"],
    ingredients: "Ketoconazole 2%",
    sideEffects: ["Skin irritation", "Burning (mild)", "Itching at application site"],
    storage: "Store below 25°C. Keep away from eyes.",
    dosageAdults: "Apply once daily to affected area for 2–4 weeks",
    dosageChildren: "As directed by physician",
    dosageMaxDaily: null,
    dosageNotes: "Continue treatment for 2 weeks after symptoms clear to prevent recurrence.",
    categorySlug: "skin-care",
  },
  {
    name: "Sunguard SPF50", slug: "sunguard-spf50",
    description: "Broad-spectrum sunscreen with UVA/UVB protection. Zinc Oxide + Titanium Dioxide.",
    price: 350, stock: 45, image: null, images: [],
    manufacturer: "BioVita", dosage: "Apply 15 min before sun exposure", form: "Cream",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["SPF 50", "UVA + UVB", "Water Resistant"],
    uses: ["Sun protection", "Sunburn prevention", "Skin cancer prevention", "Anti-aging"],
    ingredients: "Zinc Oxide 10% + Titanium Dioxide 5%",
    sideEffects: ["White cast (mild)", "Slight dryness in some skin types"],
    storage: "Store below 30°C. Keep away from direct sunlight.",
    dosageAdults: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours.",
    dosageChildren: "Safe for children 6 months and older",
    dosageMaxDaily: null,
    dosageNotes: "Reapply after swimming or sweating.",
    categorySlug: "skin-care",
  },

  // ── Diabetes Care ────────────────────────────────────────────────────────────
  {
    name: "Metfo 500", slug: "metfo-500",
    description: "First-line oral medication for type 2 diabetes. Metformin 500mg.",
    price: 55, stock: 300, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 tablet twice daily with meals", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: true,
    keyBadges: ["Type 2 Diabetes", "First Line", "Affordable"],
    uses: ["Type 2 diabetes", "Blood sugar control", "Insulin resistance", "PCOS"],
    ingredients: "Metformin Hydrochloride 500mg",
    sideEffects: ["Nausea", "Diarrhea", "Stomach upset", "Metallic taste"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet twice daily with meals",
    dosageChildren: "Not recommended under 10 years",
    dosageMaxDaily: "Maximum 2550mg per day",
    dosageNotes: "Take with food to reduce GI side effects. Monitor blood sugar regularly.",
    categorySlug: "diabetes-care",
  },
  {
    name: "Gliptin Plus", slug: "gliptin-plus",
    description: "Dual-action diabetes control with DPP-4 inhibitor. Sitagliptin + Metformin.",
    price: 280, stock: 60, image: null, images: [],
    manufacturer: "Incepta Pharma", dosage: "1 tablet twice daily", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Dual Action", "DPP-4 Inhibitor"],
    uses: ["Type 2 diabetes", "Blood sugar control", "HbA1c reduction"],
    ingredients: "Sitagliptin 50mg + Metformin Hydrochloride 500mg",
    sideEffects: ["Nasopharyngitis", "Headache", "GI upset", "Pancreatitis (rare)"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet twice daily with meals",
    dosageChildren: "Not recommended",
    dosageMaxDaily: "As prescribed by physician",
    dosageNotes: "Monitor kidney function regularly. Discontinue if pancreatitis symptoms appear.",
    categorySlug: "diabetes-care",
  },
  {
    name: "GlucoCheck Monitor", slug: "glucocheck",
    description: "Digital blood sugar meter with 25 free test strips.",
    price: 950, stock: 30, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "Test as directed by physician", form: null,
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Digital Monitor", "25 Free Strips", "Accurate"],
    uses: ["Blood sugar monitoring", "Diabetes management", "Pre-diabetes tracking"],
    ingredients: null,
    sideEffects: [],
    storage: "Store between 10–40°C. Keep away from humidity and direct sunlight.",
    dosageAdults: "Test as directed by physician, typically before and after meals",
    dosageChildren: "Safe for all ages with physician guidance",
    dosageMaxDaily: null,
    dosageNotes: "Calibrate meter before first use. Replace battery when low indicator appears.",
    categorySlug: "diabetes-care",
  },

  // ── Heart Health ─────────────────────────────────────────────────────────────
  {
    name: "Ecosprin 75", slug: "ecosprin-75",
    description: "Low-dose aspirin for heart attack and stroke prevention. Aspirin 75mg.",
    price: 30, stock: 400, image: null, images: [],
    manufacturer: "ACI Pharma", dosage: "1 tablet daily after meal", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: true,
    keyBadges: ["Heart Protection", "Stroke Prevention", "Daily Use"],
    uses: ["Heart attack prevention", "Stroke prevention", "Blood clot prevention", "Cardiovascular protection"],
    ingredients: "Aspirin (Acetylsalicylic Acid) 75mg",
    sideEffects: ["Stomach irritation", "GI bleeding (rare)", "Bruising"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet once daily after a meal",
    dosageChildren: "Not recommended for children",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "Take after food to reduce stomach irritation. Do not crush or chew.",
    categorySlug: "heart-health",
  },
  {
    name: "Atorva 10", slug: "atorva-10",
    description: "Cholesterol-lowering statin for cardiovascular health. Atorvastatin 10mg.",
    price: 75, stock: 150, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 tablet at bedtime", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Cholesterol Control", "Statin"],
    uses: ["High cholesterol", "LDL reduction", "Heart disease prevention", "Stroke prevention"],
    ingredients: "Atorvastatin Calcium 10mg",
    sideEffects: ["Muscle pain", "Liver enzyme elevation (rare)", "Headache", "Nausea"],
    storage: "Store below 25°C in a dry place away from light.",
    dosageAdults: "1 tablet once daily at bedtime",
    dosageChildren: "Not recommended under 10 years",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "Regular liver function tests recommended. Avoid grapefruit juice.",
    categorySlug: "heart-health",
  },
  {
    name: "Losartan 50", slug: "losartan-50",
    description: "ARB medication for high blood pressure management. Losartan Potassium 50mg.",
    price: 90, stock: 0, image: null, images: [],
    manufacturer: "Renata Pharma", dosage: "1 tablet daily", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Blood Pressure", "ARB", "Kidney Protective"],
    uses: ["Hypertension", "Heart failure", "Kidney protection in diabetes", "Stroke prevention"],
    ingredients: "Losartan Potassium 50mg",
    sideEffects: ["Dizziness", "Fatigue", "Low blood pressure", "Elevated potassium (rare)"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 tablet once daily",
    dosageChildren: "6 years and older with physician guidance",
    dosageMaxDaily: "Maximum 100mg per 24 hours",
    dosageNotes: "Monitor blood pressure and potassium levels regularly.",
    categorySlug: "heart-health",
  },

  // ── Eye Care ─────────────────────────────────────────────────────────────────
  {
    name: "ClearDrop", slug: "cleardrop",
    description: "Lubricating eye drops for dry eyes and computer eye strain.",
    price: 120, stock: 80, image: null, images: [],
    manufacturer: "Incepta Pharma", dosage: "1-2 drops as needed", form: "Drops",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Dry Eye Relief", "Screen Fatigue", "Preservative Free"],
    uses: ["Dry eyes", "Eye strain", "Computer vision syndrome", "Contact lens discomfort"],
    ingredients: "Carboxymethylcellulose Sodium 0.5%",
    sideEffects: ["Temporary blurred vision", "Mild stinging (transient)"],
    storage: "Store below 25°C. Discard 30 days after opening.",
    dosageAdults: "1–2 drops in each eye as needed, up to 4 times daily",
    dosageChildren: "Safe for all ages",
    dosageMaxDaily: null,
    dosageNotes: "Do not touch dropper tip to eye. Discard 30 days after opening.",
    categorySlug: "eye-care",
  },
  {
    name: "Vision Plus", slug: "vision-plus",
    description: "Eye health supplement with antioxidants for vision support. Lutein + Zeaxanthin.",
    price: 380, stock: 35, image: null, images: [],
    manufacturer: "BioVita", dosage: "1 capsule daily", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Antioxidant", "Vision Support", "Macular Health"],
    uses: ["Age-related macular degeneration", "Vision support", "Eye antioxidant protection", "Blue light protection"],
    ingredients: "Lutein 20mg + Zeaxanthin 4mg + Zinc 10mg + Vitamin C 150mg",
    sideEffects: ["Mild nausea (rare)", "Yellowing of skin (very high doses, harmless)"],
    storage: "Store in a cool dry place below 25°C.",
    dosageAdults: "1 capsule daily with a meal",
    dosageChildren: "Not recommended under 18 years",
    dosageMaxDaily: "Maximum 1 capsule per 24 hours",
    dosageNotes: "Take with food for better absorption.",
    categorySlug: "eye-care",
  },

  // ── Baby Care ────────────────────────────────────────────────────────────────
  {
    name: "Baby D Drops", slug: "baby-d-drops",
    description: "Essential vitamin D drops for infants and toddlers. Vitamin D3 400 IU.",
    price: 180, stock: 55, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "1 drop daily", form: "Drops",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Infant Safe", "Bone Development", "Immunity"],
    uses: ["Vitamin D deficiency in infants", "Bone development", "Rickets prevention", "Immunity support"],
    ingredients: "Cholecalciferol (Vitamin D3) 400 IU per drop",
    sideEffects: ["Hypercalcemia if overdosed"],
    storage: "Store below 25°C. Keep away from light. Refrigerate after opening.",
    dosageAdults: null,
    dosageChildren: "1 drop daily for infants 0–12 months. Consult doctor for toddlers.",
    dosageMaxDaily: "Maximum 1 drop per 24 hours for infants",
    dosageNotes: "Place drop on nipple, pacifier, or mix in milk. Shake before use.",
    categorySlug: "baby-care",
  },
  {
    name: "Gripe Water", slug: "gripe-water",
    description: "Natural relief for infant colic, gas and hiccups. Dill Oil + Sodium Bicarbonate.",
    price: 95, stock: 120, image: null, images: [],
    manufacturer: "ACI Pharma", dosage: "5ml 2-3 times daily", form: "Syrup",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Natural", "Colic Relief", "Alcohol Free"],
    uses: ["Infant colic", "Gas and bloating", "Hiccups", "Teething discomfort"],
    ingredients: "Dill Seed Oil 0.0046ml + Sodium Bicarbonate 125mg per 5ml",
    sideEffects: ["Allergic reaction (very rare)"],
    storage: "Store below 25°C. Refrigerate after opening. Use within 30 days.",
    dosageAdults: null,
    dosageChildren: "5ml 2–3 times daily for infants 1 month and older",
    dosageMaxDaily: "Maximum 3 doses per 24 hours",
    dosageNotes: "Shake well before use. Give after feeding.",
    categorySlug: "baby-care",
  },
  {
    name: "Baby Saline Nasal", slug: "baby-saline",
    description: "Gentle saline drops for baby nasal congestion. Sodium Chloride 0.65%.",
    price: 65, stock: 90, image: null, images: [],
    manufacturer: "Renata Pharma", dosage: "2-3 drops per nostril", form: "Drops",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Preservative Free", "Gentle", "Drug Free"],
    uses: ["Nasal congestion in babies", "Stuffy nose", "Cold symptoms", "Nasal dryness"],
    ingredients: "Sodium Chloride 0.65% in sterile water",
    sideEffects: ["None known"],
    storage: "Store below 25°C. Discard 30 days after opening.",
    dosageAdults: null,
    dosageChildren: "2–3 drops in each nostril as needed for infants and children",
    dosageMaxDaily: null,
    dosageNotes: "Tilt baby's head back slightly. Use a nasal aspirator after drops if needed.",
    categorySlug: "baby-care",
  },

  // ── Antibiotics ──────────────────────────────────────────────────────────────
  {
    name: "Moxacil 500", slug: "moxacil-500",
    description: "Broad-spectrum antibiotic for bacterial infections. Amoxicillin 500mg.",
    price: 80, stock: 200, image: null, images: [],
    manufacturer: "Square Pharma", dosage: "1 capsule 3 times daily", form: "Capsule",
    prescriptionRequired: true, isActive: true, isFeatured: true,
    keyBadges: ["Broad Spectrum", "Clinically Proven"],
    uses: ["Respiratory infections", "Ear infections", "Urinary tract infections", "Skin infections", "Dental infections"],
    ingredients: "Amoxicillin Trihydrate 500mg",
    sideEffects: ["Diarrhea", "Nausea", "Rash", "Allergic reaction (in penicillin-allergic patients)"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 capsule 3 times daily for 7–10 days",
    dosageChildren: "25mg/kg/day in divided doses",
    dosageMaxDaily: "Maximum 3g per 24 hours",
    dosageNotes: "Complete the full course even if symptoms improve. Take with or without food.",
    categorySlug: "antibiotics",
  },
  {
    name: "Azith 250", slug: "azith-250",
    description: "Macrolide antibiotic for respiratory and skin infections. Azithromycin 250mg.",
    price: 120, stock: 140, image: null, images: [],
    manufacturer: "Beximco Pharma", dosage: "2 tablets day 1, then 1 daily", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["5-Day Course", "Once Daily", "Z-Pack"],
    uses: ["Community-acquired pneumonia", "Bronchitis", "Skin infections", "Strep throat", "STI"],
    ingredients: "Azithromycin Dihydrate 250mg",
    sideEffects: ["Diarrhea", "Nausea", "Abdominal pain", "QT prolongation (rare)"],
    storage: "Store below 30°C in a dry place.",
    dosageAdults: "500mg (2 tablets) on day 1, then 250mg (1 tablet) daily for 4 days",
    dosageChildren: "10mg/kg on day 1, then 5mg/kg for 4 days",
    dosageMaxDaily: "Maximum 500mg per 24 hours",
    dosageNotes: "Take on an empty stomach for better absorption. Complete the full course.",
    categorySlug: "antibiotics",
  },
  {
    name: "Cipro 500", slug: "cipro-500",
    description: "Fluoroquinolone antibiotic for urinary and respiratory infections. Ciprofloxacin 500mg.",
    price: 95, stock: 0, image: null, images: [],
    manufacturer: "Incepta Pharma", dosage: "1 tablet twice daily", form: "Tablet",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Fluoroquinolone", "Broad Spectrum"],
    uses: ["UTI", "Respiratory infections", "GI infections", "Bone infections", "Skin infections"],
    ingredients: "Ciprofloxacin Hydrochloride 500mg",
    sideEffects: ["Nausea", "Diarrhea", "Dizziness", "Tendon rupture (rare)", "Photosensitivity"],
    storage: "Store below 25°C in a dry place away from light.",
    dosageAdults: "1 tablet twice daily for 7–14 days",
    dosageChildren: "Not recommended as first-line in children",
    dosageMaxDaily: "Maximum 1500mg per 24 hours",
    dosageNotes: "Drink plenty of water. Avoid antacids within 2 hours. Use sunscreen outdoors.",
    categorySlug: "antibiotics",
  },
  {
    name: "Cephrad 250", slug: "cephrad-250",
    description: "First-generation cephalosporin for skin and soft tissue infections. Cephalexin 250mg.",
    price: 70, stock: 100, image: null, images: [],
    manufacturer: "ACI Pharma", dosage: "1 capsule 4 times daily", form: "Capsule",
    prescriptionRequired: true, isActive: true, isFeatured: false,
    keyBadges: ["Cephalosporin", "Skin Infections"],
    uses: ["Skin infections", "Soft tissue infections", "Bone infections", "Respiratory tract infections"],
    ingredients: "Cephalexin Monohydrate 250mg",
    sideEffects: ["Diarrhea", "Nausea", "Rash", "Allergic reaction"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "1 capsule 4 times daily for 7–14 days",
    dosageChildren: "25–50mg/kg/day in divided doses",
    dosageMaxDaily: "Maximum 4g per 24 hours",
    dosageNotes: "May be taken with food to reduce GI upset. Complete the full course.",
    categorySlug: "antibiotics",
  },

  // ── First Aid ────────────────────────────────────────────────────────────────
  {
    name: "Savlon Antiseptic", slug: "savlon-antiseptic",
    description: "Antiseptic liquid for wound cleaning and infection prevention.",
    price: 85, stock: 160, image: null, images: [],
    manufacturer: "ACI Pharma", dosage: "Apply diluted to affected area", form: null,
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["First Aid", "Antiseptic", "Trusted Brand"],
    uses: ["Wound cleaning", "Infection prevention", "Skin disinfection", "Minor cuts", "Abrasions"],
    ingredients: "Chlorhexidine Gluconate 0.3% + Cetrimide 0.5%",
    sideEffects: ["Skin irritation (rare)", "Contact dermatitis (rare)"],
    storage: "Store below 30°C away from direct sunlight.",
    dosageAdults: "Dilute 1:30 with water for wound cleaning. Apply with cotton wool.",
    dosageChildren: "Use diluted solution (1:30). Avoid contact with eyes.",
    dosageMaxDaily: null,
    dosageNotes: "Always dilute before use. Do not use in eyes or ears.",
    categorySlug: "first-aid",
  },
  {
    name: "Elastic Bandage Roll", slug: "elastic-bandage",
    description: "Stretchable bandage for sprains, strains and wound support. Cotton Elastic 4 inch.",
    price: 45, stock: 200, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "Wrap firmly around affected area", form: null,
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Reusable", "Latex Free", "4 inch"],
    uses: ["Sprains", "Strains", "Joint support", "Wound dressing", "Compression therapy"],
    ingredients: "100% Cotton Elastic",
    sideEffects: ["Skin irritation if too tight"],
    storage: "Store in a clean dry place.",
    dosageAdults: "Wrap firmly but not too tight. Check circulation regularly.",
    dosageChildren: "Use smaller sizes for children",
    dosageMaxDaily: null,
    dosageNotes: "Do not wrap too tightly. Check for numbness or tingling.",
    categorySlug: "first-aid",
  },
  {
    name: "Burnol Cream", slug: "burnol-cream",
    description: "Antiseptic burn cream for minor burns and scalds.",
    price: 60, stock: 110, image: null, images: [],
    manufacturer: "Renata Pharma", dosage: "Apply gently on burn area", form: "Cream",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Burn Relief", "Antiseptic", "Soothing"],
    uses: ["Minor burns", "Scalds", "Sunburn", "Skin irritation", "Wound protection"],
    ingredients: "Aminacrine HCl 0.1% + Cetrimide 0.5%",
    sideEffects: ["Skin sensitization (rare)", "Mild stinging on application"],
    storage: "Store below 25°C in a dry place.",
    dosageAdults: "Apply gently to affected area 2–3 times daily",
    dosageChildren: "Safe for children. Apply gently.",
    dosageMaxDaily: null,
    dosageNotes: "Cool burn with cold water first for 10 minutes before applying.",
    categorySlug: "first-aid",
  },

  // ── Mental Wellness ──────────────────────────────────────────────────────────
  {
    name: "Melatonin 3", slug: "melatonin-3",
    description: "Natural sleep aid for insomnia and jet lag. Melatonin 3mg.",
    price: 220, stock: 70, image: null, images: [],
    manufacturer: "BioVita", dosage: "1 tablet 30 min before bedtime", form: "Tablet",
    prescriptionRequired: false, isActive: true, isFeatured: true,
    keyBadges: ["Natural Sleep Aid", "Non-Habit Forming", "Jet Lag Relief"],
    uses: ["Insomnia", "Jet lag", "Sleep disorders", "Shift work sleep disorder"],
    ingredients: "Melatonin 3mg",
    sideEffects: ["Drowsiness next morning", "Headache (rare)", "Dizziness (rare)"],
    storage: "Store below 25°C in a dry place away from light.",
    dosageAdults: "1 tablet 30 minutes before bedtime",
    dosageChildren: "Not recommended under 18 years without physician guidance",
    dosageMaxDaily: "Maximum 1 tablet per 24 hours",
    dosageNotes: "Avoid screen exposure after taking. Do not drive after use.",
    categorySlug: "mental-wellness",
  },
  {
    name: "StressEase", slug: "stress-ease",
    description: "Herbal stress relief with adaptogenic ashwagandha root. Ashwagandha 600mg + B-Complex.",
    price: 350, stock: 45, image: null, images: [],
    manufacturer: "BioVita", dosage: "1 capsule twice daily", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Adaptogen", "Stress Relief", "Natural"],
    uses: ["Stress", "Anxiety", "Fatigue", "Mental clarity", "Adrenal support"],
    ingredients: "Ashwagandha Root Extract 600mg + Vitamin B-Complex",
    sideEffects: ["Mild GI upset (rare)", "Drowsiness (rare)"],
    storage: "Store in a cool dry place below 25°C.",
    dosageAdults: "1 capsule twice daily with meals",
    dosageChildren: "Not recommended under 18 years",
    dosageMaxDaily: "Maximum 2 capsules per 24 hours",
    dosageNotes: "Best taken consistently for 4–8 weeks for optimal results.",
    categorySlug: "mental-wellness",
  },
  {
    name: "CalmPlus", slug: "calm-plus",
    description: "Promotes relaxation and mental clarity without drowsiness. L-Theanine 200mg + Magnesium.",
    price: 280, stock: 0, image: null, images: [],
    manufacturer: "Healthcare Pharma", dosage: "1 capsule daily", form: "Capsule",
    prescriptionRequired: false, isActive: true, isFeatured: false,
    keyBadges: ["Non-Drowsy", "Relaxation", "Focus"],
    uses: ["Anxiety relief", "Mental focus", "Relaxation", "Stress management", "Sleep quality"],
    ingredients: "L-Theanine 200mg + Magnesium Glycinate 150mg",
    sideEffects: ["Mild headache (rare)", "GI discomfort (rare)"],
    storage: "Store in a cool dry place below 25°C.",
    dosageAdults: "1 capsule daily, preferably in the morning",
    dosageChildren: "Not recommended under 18 years",
    dosageMaxDaily: "Maximum 1 capsule per 24 hours",
    dosageNotes: "Can be taken with or without food. Non-habit forming.",
    categorySlug: "mental-wellness",
  },
]

// ── Main seed function ────────────────────────────────────────────────────────
async function seedMedicines() {
  console.log("🌱 Starting seed...\n")

  const SELLER_ID = await resolveSellerId()
  console.log(`👤 Using seller ID: ${SELLER_ID}\n`)

  // Step 1: Upsert categories
  console.log("📂 Upserting categories...")
  const categoryMap = new Map<string, string>()

  for (const cat of categories) {
    const result = await prisma.category.upsert({
      where: { slug: cat.slug },
      create: cat,
      update: {},
    })
    categoryMap.set(cat.slug, result.id)
    console.log(`   ✓ ${cat.name}`)
  }

  // Step 2: Upsert medicines
  console.log("\n💊 Upserting medicines...")
  let created = 0
  let skipped = 0

  for (const med of medicines) {
    const categoryId = categoryMap.get(med.categorySlug)
    if (!categoryId) {
      console.warn(`   ⚠ No category found for slug "${med.categorySlug}", skipping ${med.name}`)
      skipped++
      continue
    }

    const { categorySlug, ...medData } = med

    await prisma.medicine.upsert({
      where: { slug: med.slug },
      create: { ...medData, categoryId, sellerId: SELLER_ID },
      update: {},
    })

    console.log(`   ✓ ${med.name}`)
    created++
  }

  console.log(`\n✅ Seed complete! ${created} medicines upserted, ${skipped} skipped.`)
}

seedMedicines()
  .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1) })
  .finally(() => prisma.$disconnect())
